IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'PBL')
BEGIN
    CREATE DATABASE PBL;
END
GO
USE PBL;
GO

CREATE TABLE Usuarios (
    IdUsuario INT PRIMARY KEY IDENTITY(1,1),
	Login NVARCHAR(50) UNIQUE NOT NULL,
    Senha NVARCHAR(255) NOT NULL,
    Nome NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    DataNascimento DATE,
    Telefone NVARCHAR(20),
	DataRegistro DATETIME NOT NULL DEFAULT GETDATE()
);
GO
CREATE TABLE Empresas (
    IdEmpresa INT PRIMARY KEY IDENTITY(1,1),
    NomeEmpresa NVARCHAR(150) NOT NULL,
    CNPJ NVARCHAR(20) NOT NULL UNIQUE, 
    Endereco NVARCHAR(255) NOT NULL,
    Telefone NVARCHAR(20),
    Email NVARCHAR(100),
    DataCadastro DATETIME NOT NULL DEFAULT GETDATE()
);
GO
CREATE TABLE Estufas (
    IdEstufa INT PRIMARY KEY IDENTITY(1,1),
	IdUsuario INT NOT NULL,
    IdEmpresa INT NOT NULL,    
    Modelo NVARCHAR(50) NOT NULL,    
    Descricao NVARCHAR(255) NULL,
	Preco money ,
	PeriodoLocacao INT NOT NULL CHECK (PeriodoLocacao > 0),
    DataCadastro DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (IdEmpresa) REFERENCES Empresas(IdEmpresa) ON DELETE CASCADE,
	FOREIGN KEY (IdUsuario) REFERENCES Usuarios(IdUsuario) ON DELETE CASCADE
);
